-- ============================================================================
--  schema.sql  -  H2 schema (runs before data.sql on startup)
--
--  AUDIT FIX #1: this file previously used  BIGINT PRIMARY KEY AUTO_INCREMENT.
--  AUTO_INCREMENT is MySQL syntax. Our JDBC URL says MODE=PostgreSQL, and
--  H2 2.x in PostgreSQL mode REJECTS it -> the app would crash on startup.
--  `GENERATED BY DEFAULT AS IDENTITY` is standard SQL: it works in H2 (all
--  modes) AND real PostgreSQL, and matches JPA GenerationType.IDENTITY.
--  Lesson: always test DDL against the compatibility mode you configured.
-- ============================================================================

DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS show_event;

CREATE TABLE show_event (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT       NOT NULL,
    title       VARCHAR(200) NOT NULL,
    venue       VARCHAR(200) NOT NULL,
    total_seats INT          NOT NULL,
    price_cents BIGINT       NOT NULL,
    starts_at   TIMESTAMP    NOT NULL,
    -- Optimistic locking counter (see Show.java @Version). Hibernate increments
    -- it on every UPDATE and adds "WHERE version = ?" - a concurrent editor
    -- whose version is stale gets 0 rows updated -> OptimisticLockException.
    version     BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_show_tenant ON show_event(tenant_id);

CREATE TABLE booking (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT       NOT NULL,
    show_id      BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    seat_no      VARCHAR(10)  NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    price_cents  BIGINT       NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_booking_show FOREIGN KEY (show_id) REFERENCES show_event(id),
    CONSTRAINT uk_show_seat UNIQUE (show_id, seat_no)     -- prevents double-booking
);

-- Keyset index: exactly matches ORDER BY tenant_id, created_at DESC, id DESC
-- Leftmost prefix: WHERE tenant_id = ? uses the index, then the sort columns
-- are already in order so no filesort. Page 5000 costs the same as page 1.
CREATE INDEX idx_booking_feed
    ON booking (tenant_id, created_at DESC, id DESC);

-- Convenience index for status filters
CREATE INDEX idx_booking_status ON booking (tenant_id, status);
